---
output:
  html_document:
    df_print: paged
---

# Reversible Metabolism

```{r setup, message = FALSE}
# setup

library(deSolve)
library(wnl)
library(ggplot2)
library(dplyr)
library(readr)
library(purrr)
library(tidyr)
library(forcats)
library(ggsci)

c('fit_data_all')

# functions ----

round_df <- function(x, digits) {
  # round all numeric variables
  # x: data frame 
  # digits: number of digits to round
  numeric_columns <- sapply(x, mode) == 'numeric'
  x[numeric_columns] <-  round(x[numeric_columns], digits)
  x
}

PKde <- function(t, y, p) # used for lsoda
{
  cInf = infusion_history[[cID]]
  Rate1 = cInf[findInterval(t, cInf[,"TIME"]),"RATE1"]
  Rate2 = cInf[findInterval(t, cInf[,"TIME"]),"RATE2"]
  
  Ke1 = p["CLp"]/p["Vc"]
  Ke2 = p["CLm"]/p["Vm"]
  
  K12 = p["CLd1"]/p["Vc"]
  K21 = p["CLd2"]/p["Vm"]
  
  dy1dt = Rate1/p["Vc"] - Ke1*y[1] - K12*y[1] + K21*y[2]
  dy2dt = Rate2/p["Vm"] - Ke2*y[2] + K12*y[1] - K21*y[2]
  
  return(list(c(dy1dt, dy2dt)))  
}

fPK34 = function(THETA)
{
  Vc   = THETA[1]
  Vm   = THETA[2]
  CLp  = THETA[3]
  CLm  = THETA[4]
  CLd1 = THETA[5]
  CLd2 = THETA[6]

  y = vector()
  for (i in 1:nID) {
    cID <<- IDs[i] # referencing wihtin PKde
    cy = deSolve::lsoda(y=c(0, 0), 
                        times=TIME, 
                        func=PKde, 
                        parms=c(Vc=Vc, Vm=Vm, 
                                CLp=CLp, CLm=CLm, 
                                CLd1=CLd1, CLd2=CLd2))
    iTime1 = TIME %in% dPK34[dPK34$ID==cID & dPK34$MOL == "Cp", "TIME"]
    iTime2 = TIME %in% dPK34[dPK34$ID==cID & dPK34$MOL == "Cm", "TIME"]
    y = c(y, cy[iTime1,"1"], cy[iTime2,"2"])
  }
  return(y)
}

fit_lsoda <- function(scenario) {
  cID <<- scenario
  deSolve::lsoda(y=c(0, 0), 
                 times=TIME, 
                 func=PKde, 
                 parms=point_estimates) %>% 
    as.data.frame() %>% 
    select(TIME = 1, Cp = 2, Cm = 3) %>% 
    dplyr::mutate(ID = cID)
}

df_scenario <- function(df){
  df %>% 
    mutate(scenario = case_when(
      ID==1 ~ 'IV infusion (60min) of parent (120mg)\n + metabolite (6mg)',
      ID==2 ~ 'IV infusion (5min) of metabolite (20mg)'
    )) %>% 
    mutate(scenario = as_factor(scenario)) %>% 
    print()
}
```


# 자료

한 개인에서 두가지의 시나리오로 약을 먹은 뒤의 농도-시간 자료를 얻어낸 것입니다.

```{r}
raw_dPK34 <- read_csv('data-raw/reversible-metabolism.csv', 
                      skip = 2,
                      col_names = c("TIME", "MOL", "DV", "ID", "DV_mock")) %>% 
  select(-DV_mock) %>%  # Unit: TIME min, DV umol
  print()
```

```{r}
raw_dPK34 %>% 
  unite(col = 'class', MOL, ID) %>% 
  spread(class, DV) %>% 
  select(1, 4, 2, 5, 3)
```

# 자료의 탐색

```{r infusion_history}
S1 <- data.frame(TIME=c(0, 60), 
                 RATE1=c(2,0), 
                 RATE2=c(0.1, 0))
S2 <- data.frame(TIME=c(0,5), 
                 RATE1=c(0, 0), 
                 RATE2=c(4, 0))

infusion_history <- list(S1, S2) %>% 
  print()
```

```{r}
raw_data <- raw_dPK34 %>% 
  mutate(scenario = case_when(
    ID==1 ~ 'IV infusion (60min) of parent (120mg)\n + metabolite (6mg)',
    ID==2 ~ 'IV infusion (5min) of metabolite (20mg)'
  )) %>% 
  mutate(scenario = as_factor(scenario))

ggplot(data = raw_data, 
       aes(x = TIME, y = DV, group = interaction(ID, MOL), 
           color = MOL)) +
  geom_line(linetype = 3) +
  geom_point(size = 2) + 
  theme_bw() +
  facet_wrap(. ~ scenario) +
  labs(color = 'Molecules', shape = 'Infusion', 
       x = 'Time (min)', y = 'Concentration (umol/L)',
       title = 'Observed concentration') +
  ggsci::scale_color_nejm() +
  scale_x_continuous(breaks = c(0, 30, 60, 90, 120, 150))

ggsave('assets/figure-pk.pdf', width = 8, height = 5)
```

- Scenario 1
* AMTp = 164.1 mg/ RATE = 2.735 mg/min / 60 min
* AMTm = 3.9 mg / RATE = 0.065 mg/min / 60 min

- Scenario 2
* AMTm = 10 mg / RATE = 2 mg/min / 5 min

```{r final_fit_takes_long, cache = TRUE}
dPK34 <- raw_dPK34 %>% 
  as.data.frame()

TIME <- c(0, dPK34$TIME) %>% unique() %>% sort()
IDs = unique(dPK34[,"ID"])
nID = length(IDs)

# fPK34(c(14.1169, 2.96671, 0.445693, 0.00833429, 0.00308422, 0.0632217))

final_fit <- wnl::nlr(Fx = fPK34, # Function for structural model
                      Data = dPK34, # Data table
                      pNames=c("Vc", "Vm", "CLp", "CLm", "CLd1", "CLd2"), 
                      IE=c(15, 3, 0.5, 0.01, 0.003, 0.1), 
                      Error="P")  # Error model: "P" for proportional error

final_fit

# Vc  12.3 vs 14.1 (R vs WinNonlin, NONMEM)
# AIC -131.0377 vs -131.05554 (R vs WinNonlin)
```

```{r}
e$r # -214.8824 vs -214.895 (R vs NONMEM)
```

```{r}
point_estimates <- final_fit$Est[1, c('Vc', 'Vm', 'CLp', 'CLm', 'CLd1', 'CLd2')] %>% 
  print()
```

```{r}
fit_dPK34 <- bind_rows(fit_lsoda(1), fit_lsoda(2)) %>% 
  gather(MOL, PRED, Cp:Cm) %>% 
  print()


#fit_data_all <- bind_rows(raw_dPK34, fit_dPK34) %>% 
fit_data_all <- full_join(raw_dPK34, fit_dPK34) %>% 
  df_scenario()
```

```{r fit_data_figure}
ggplot(data = fit_data_all, 
       aes(x = TIME, y = DV, group = interaction(ID, MOL), 
           color = MOL)) +
  geom_line(aes(y=PRED), size = 1) +
  geom_point(size = 2) + 
  theme_bw() +
  facet_wrap(. ~ scenario) +
  labs(color = 'Molecules', shape = 'Infusion', 
       x = 'Time (min)', y = 'Concentration (umol/L)',
       title = 'Predicted (lines) and observed (points) concentration') +
  ggsci::scale_color_nejm() +
  scale_x_continuous(breaks = c(0, 30, 60, 90, 120, 150))

ggsave('assets/figure-pk-fit.pdf', width = 8, height = 5)
```


```{r}
# Simulations

infusion_history <- as.list(expand.grid(TIME = c(5, 15, 30, 60),
                                        RATE1 = seq(0, 5, by = 1), 
                                        RATE2 = seq(0, 5, by = 1))) %>% 
  pmap(~ data.frame(TIME = c(0, ..1), 
                    RATE1 = c(..2, 0), 
                    RATE2 = c(..3, 0)))

final_names <- infusion_history %>%
  map(~ .x %>% 
        summarise_all(funs(sum)) %>% 
        unite(col = final_name, TIME, RATE1, RATE2)) %>% 
  bind_rows() %>% 
  .$final_name

simulation_df <- 1:length(infusion_history) %>% 
  map(fit_lsoda) %>% 
  map2(.y = final_names, .f = ~ mutate(.x, final_name = .y)) %>% 
  bind_rows() %>% 
  gather(MOL, PRED, Cp:Cm) %>% 
  as_tibble() %>% 
  separate(col = final_name, into = c('DURATION', 'RATE1', 'RATE2')) %>% 
  mutate_at(vars(DURATION, RATE1, RATE2), funs(as.numeric)) %>% 
  mutate(RATE1 = sprintf('P %0.0fmg/min', RATE1)) %>% 
  mutate(RATE2 = sprintf('M %0.0fmg/min', RATE2)) %>% 
  print()

plot_simulation <- function(df) ggplot(df, 
       aes(x = TIME, y=PRED, group = interaction(ID, MOL), 
           color = MOL, shape = MOL)) +
  geom_line() +
  theme_bw() +
  facet_grid(rows = vars(RATE1), cols = vars(RATE2)) +
  labs(color = 'Molecules', shape = 'Infusion', 
       x = 'Time (min)', y = 'Concentration (umol/L)') +
  ggsci::scale_color_nejm() +
  scale_x_continuous(breaks = c(0, 60, 120)) +
  theme(legend.position='top')

p05 <- simulation_df %>% filter(DURATION == 5) %>% plot_simulation() +
  ggtitle('Simulation of IV infusion (5 min)')
p15 <- simulation_df %>% filter(DURATION == 15) %>% plot_simulation() +
  ggtitle('Simulation of IV infusion (15 min)')
p30 <- simulation_df %>% filter(DURATION == 30) %>% plot_simulation() +
  ggtitle('Simulation of IV infusion (30 min)')
p60 <- simulation_df %>% filter(DURATION == 60) %>% plot_simulation() +
  ggtitle('Simulation of IV infusion (60 min)')

cowplot::plot_grid(p05, p15, p30, p60, ncol = 2, labels = LETTERS[1:4])
ggsave('assets/simulation.pdf', width = 14, height = 20)
```

```{r simulation_small, eval = FALSE}
simulation_1 <- data.frame(TIME = c(0, 60),
                           RATE1 = c(10, 0),
                           RATE2 = c(1.5, 0))

simulation_2 <- data.frame(TIME = c(0, 120),
                           RATE1 = c(5, 0),
                           RATE2 = c(0.75, 0))

infusion_history <- list(simulation_1, simulation_2) %>% 
  print()

TIME <- seq(0, 180, by = 5)

1:length(infusion_history) %>% 
  map(fit_lsoda) %>% 
  bind_rows() %>% 
  gather(MOL, PRED, Cp:Cm) %>% 
  df_scenario() %>% 
  ggplot(aes(x = TIME, y=PRED, group = interaction(ID, MOL), 
             color = MOL)) +
  geom_line() +
  #geom_point() + 
  theme_bw() +
  facet_wrap(. ~ scenario) +
  labs(color = 'Molecules', shape = 'Infusion', 
       x = 'Time (min)', y = 'Concentration (umol/L)') +
  ggsci::scale_color_nejm() +
  scale_x_continuous(breaks = c(0, 30, 60, 90, 120, 150))
```

```{r figure_old, eval = FALSE}
## Figure 34.1, p 639
plot(0, 0, type="n", xlim=c(0, 180), ylim=c(0, 6), xlab="Time (min)", ylab="Concentration (uM)")

IDs = unique(dPK34[,"ID"])
nID = length(IDs)

# point_estimates <- c(Vc=14.1169, Vm=2.96671, 
#                      CLp=0.445693, CLm=0.00833429, 
#                      CLd1=0.00308422, CLd2=0.0632217)

y = vector()
for (i in 1:nID) {
  cID <<- IDs[i] # referencing wihtin PKde
  cy <- lsoda(y=c(0, 0), 
              times=TIME, 
              func=PKde, 
              parms=point_estimates)
  iTime1 = TIME %in% dPK34[dPK34$ID==cID & dPK34$MOL == "Cp", "TIME"]
  iTime2 = TIME %in% dPK34[dPK34$ID==cID & dPK34$MOL == "Cm", "TIME"]
  points(dPK34[dPK34$ID==cID & dPK34$MOL == "Cp", "TIME"], 
         dPK34[dPK34$ID==cID & dPK34$MOL == "Cp", "DV"], pch=19, col=i)
  points(dPK34[dPK34$ID==cID & dPK34$MOL == "Cm", "TIME"], 
         dPK34[dPK34$ID==cID & dPK34$MOL == "Cm", "DV"], pch=15, col=i)
  lines(TIME, cy[,"1"], col=i)
  lines(TIME, cy[,"2"], lty=2, col=i)
  y = c(y, cy[iTime1,"1"], cy[iTime2,"2"])
} ; y
```



